language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_VERSION='>=1.4,<1.5'
  - DJANGO_VERSION='>=1.5,<1.6'
  - DJANGO_VERSION='>=1.6,<1.7'
install:
  - pip install "Django${DJANGO_VERSION}"
  - pip install .
script: cd tests; ./manage.py test ksp_login_tests
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION='>=1.4,<1.5'
    - python: "3.3"
      env: DJANGO_VERSION='>=1.4,<1.5'
