language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION='>=1.11,<1.12'
  - DJANGO_VERSION='>=2.0,<2.1'
  - DJANGO_VERSION='>=2.1,<2.2'
install:
  - pip install "Django${DJANGO_VERSION}"
  - pip install -e .
  - pip install coverage coveralls
script: coverage run ./tests/manage.py test ksp_login_tests
after_success: coveralls
