language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION='>=1.8,<1.9'
  - DJANGO_VERSION='>=1.9,<1.10'
  - DJANGO_VERSION='>=1.10,<1.11'
install:
  - pip install "Django${DJANGO_VERSION}"
  - pip install -e .
  - pip install coverage coveralls
script: coverage run ./tests/manage.py test ksp_login_tests
after_success: coveralls
